#!/bin/bash
# ====================================================
# convert4car - Script to convert your multiformat music library
#               in mp3. Supported format ogg, flac
# ====================================================
# @authors: Massimo Barbieri (massimo@fsfe.org)
# @Mantainer: Massimo Barbieri (massimo@fsfe.org) 
# @copyright 2020, 2022
# Depends: bash (>= 2.05a-11), ffmpeg, libmp3lame-dev
# ====================================================
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU GENERAL PUBLIC LICENSE
# License as published by the Free Software Foundation; either 
# version 3 of the License, or any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU AFFERO GENERAL PUBLIC LICENSE for more details.
#  
# You should have received a copy of the GNU Lesser General Public 
# License along with this library.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################

#TODO: Aggiungere funzione per scaricare le copertine nella cartella

# Controllo l'esistenza dei parametri necessari al funzionamento dello script
if [ "$1" == "" ] || [ "$2" == "" ]
then
	echo "Usage $0 <path of the music folder> <path of the destination folder."
	echo ""
	exit 1
fi

# Percorso della cartella che contiene la tua musica.
# Esempio /home/pippo/Music
MUSICFOLDER=$1;

# Percorso della cartella nella quale saranno salvati i file convertiti
# Esempio /home/pippo/Car
CARFOLDER=$2;



# Checking required packages
REQUIRED_PKG=(libmp3lame-dev ffmpeg)

for PKG in ${REQUIRED_PKG[@]}
do
	PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $PKG|grep "install ok installed")
echo Checking for $PKG: $PKG_OK

if [ "" = "$PKG_OK" ]; then
  echo "Ops! $PKG is not installed. Please install it and run the script again."
  echo "To install the package you should run sudo apt install $PKG"
  exit
fi
done




shopt -s globstar
cd $MUSICFOLDER

# Crea la cartella di destinazione se non c'è
if [ -d "$CARFOLDER" ] ; then
	echo "La cartella $CARFOLDER è presente"
else
	echo "Creo la cartella"
	mkdir $CARFOLDER
fi

# LISTA TUTTI I FILE E CARTELLE
for i in **/*; do # Whitespace-safe and recursive



	# Se è una cartella
	if [ -d "$i" ] ; then

		# Se è una cartella controllo se esiste nell'archivio auto
		# se non esiste la creo
		if [ ! -d "$CARFOLDER/$i" ] ; then
			echo "$CARFOLDER/$i non è presente, creo la cartella..."
			mkdir "$CARFOLDER/$i"
		fi

	# Se è un file
	elif [ -f "$i" ] ; then
		# Estraggo l'estensione
		filename="${i##*/}" ; extension="${filename##*.}"
		
		#echo "$i è un file $extension" #DEBUG

		
		case $extension in
			mp3)
				# Controllo se nella cartella che contiene il file è presente
				# un file cover.jpg o front.jpg
				# se è presente anziché fare una copia con cp la faccio con
				# ffmpeg
				DIROFMP3=$(dirname $i)
				echo $DIROFMP3

			#	if [ ! -f "$DIROFMP3/cover.jpg" ]
			#	then
			#		COVER="$DIROFMP3/cover.jpg"
			#	fi
			#	if [ -f "DIROFMP3/front.jpg" ]
			#		COVER="$DIROFMP3/front.jpg"
	#	fi

				echo "Trovato file mp3..."
				if [ ! -f "$CARFOLDER/$i" ] ; then

					echo "$filename non esiste in CARFOLDER lo copio..."
					cp "$i" "$CARFOLDER/$i"
				else
					echo "$filename è già presente in car folder :-)"
				fi
				;;
			ogg|flac)
				echo "Trovato file ogg...";
				BASENAME=$(echo "$i" | cut -f 1 -d '.') # NOME FILE SENZA ESTENSIONE

				if [ ! -f "$CARFOLDER/$BASENAME.mp3" ] ; then
					echo "$CARFOLDER/$BASENAME.mp3 non esiste in CARFOLDER lo converto..."
					ffmpeg -i "$i" -acodec libmp3lame -map_metadata 0:s:0 "$CARFOLDER/$BASENAME.mp3"
				else
					echo "$BASENAME.mp3 è già presente in car folder :-)"
				fi
				;;

# Occorre aggiungere con ffmpeg l'inserimento della cover all'interno del file
#			jpg)
#				echo "Trovato file jpg....forse è l'artwork dell'album?"
#				if [ ! -f "$CARFOLDER/$i" ] ; then
#					echo "$filename non esiste in CARFOLDER lo copio..."
#					cp "$i" "$CARFOLDER/$i"
#				else
#					echo "$filename è già presente in car folder :-)"
#				fi
#				;;

			*)
				echo "Non conosco il file $extension";
		esac


	else
		echo "Trovato file $i sconosciuto, consulta i log..."
		echo "Non riconosco il file $i" >> convert-error.log
	fi
done












